// <auto-generated />
using System;
using LotoTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LotoTest.Migrations
{
    [DbContext(typeof(LottoDbContext))]
    partial class LottoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LotoTest.LotteryCombination", b =>
                {
                    b.Property<int>("CombinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CombinationId"), 1L, 1);

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CombinationId");

                    b.ToTable("LotteryCombinations");
                });
#pragma warning restore 612, 618
        }
    }
}
